version: "3"

services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fig_sell_db
  fig-sell:
    container_name: fig-sell-exec
    build: .
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    restart: on-failure
